
LIB_NAME	:= chutil
DEPS		:= chsys
SRCS		:= list.c \
			   list_helpers.c \
			   map.c \
			   heap.c \
			   string.c \
			   stream.c \
			   utf8.c

TEST_SRCS   := main.c \
			   list.c \
			   list_helpers.c \
			   map.c \
			   heap.c \
			   string.c \
			   stream.c \
			   utf8.c

include ../stub.mk
